### ISSUE TITLE
数据标签咨询

### ISSUE THREAD

**Issue by gdut-zqr** [hannshu/st_datasets#1]
作者您好，根据本仓库中的数据，我成功获取了经过整理的h5ad文件，感谢！其中有两个数据集（mouse olfactory bulb dataset | 10x Genomics Visium，mouse olfactory bulb dataset | Stereo-seq）我在其他地方没能找到相应的标签数据，您可以给出这两个数据集的标签数据的来源吗，谢谢

**Comment by hannshu** [comment]
[gdut-zqr](https://github.com/gdut-zqr)您好

带标签的 Stereo-seq 获得的小鼠嗅球数据集是从此 [文章](https://doi.org/10.1093/bib/bbac475) 转换而来，目前已弃用；如果您仍想使用带标签的版本，请使用此 [提交](https://github.com/hannshu/st_datasets/tree/c56d877a001071cb7b2cb4c222491ce20e026c22)。更详细的信息请您参见README。  
对于 visium 获得的小鼠嗅球数据集，标签来自[STomicsDB](https://db.cngb.org/stomics/datasets/STDS0000107)并存储在 adata.obs['clusters'] 中。

---

Hi [gdut-zqr](https://github.com/gdut-zqr),

The annotated Stereo-seq obtained mouse olfactory bulb dataset is converted from this [article](https://doi.org/10.1093/bib/bbac475) and currently deprecated; if you still want to use the annotated version, please use this [commit](https://github.com/hannshu/st_datasets/tree/c56d877a001071cb7b2cb4c222491ce20e026c22). For more detailed information, please refer to the README.  
For the visium obtained mouse olfactory bulb dataset, the label is derived from [STomicsDB](https://db.cngb.org/stomics/datasets/STDS0000107) and stored at adata.obs['clusters'].

**Comment by gdut-zqr** [comment]
Thank you so much!
